---
title: 'Discover 2015 júl: workshopy a program'
output:
  html_document:
    css: custom.css
    fig_height: 8
    fig_width: 8
    number_sections: no
    toc: yes
    toc_depth: 1
---
  
  Discover 2015 júl: program a organizace
==============
----------
  
*[Zpět na rozcestník zpětné vazby](index.html)*
  
  
```{r Prep, echo=F, include=F}

library(knitr)
library(Cairo)
# set up graphing:
opts_chunk$set(echo=FALSE, dev='CairoPNG', warning=FALSE)
# make relative references work - change this to project directory
opts_knit$set(root.dir='~/github/discover2015/d15eval/')

CairoFonts(
  regular="Gill Sans MT:style=Regular",
  bold="Gill Sans MT:style=Bold",
  italic="Gill Sans MT:style=Italic",
  bolditalic="Gill Sans MT:style=Bold Italic,BoldItalic",
  symbol="Symbol"
)

setwd("~/github/discover2015/d15eval/")
source("./d15eval_setup.R")
setwd("~/github/discover2015/d15eval/")

```

# Program obecně

```{r Program, echo=F, dev="CairoPNG",fig.cap="",dpi=200, fig.retina=2}


```

## Komunikace

### Před Discover

### Brožurka